spring:
  datasource:
    url: jdbc:mysql://localhost:3306/bookdam?serverTimezone=Asia/Seoul
    username: bookdam
    password: bookdam
  jpa:
    hibernate:
      ddl-auto: update # ??: update, ??: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  data:
    redis:
      host: localhost
      port: 6379
